{
 "title": "climat in pc room",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  measure_timestamp AS \"time\",\n  temperature\nFROM climate\nWHERE\n  $__timeFilter(measure_timestamp)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  measure_timestamp AS \"time\",\n  humidity\nFROM climate\nWHERE\n  $__timeFilter(measure_timestamp)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  measure_timestamp AS \"time\",\n  pressure\nFROM climate\nWHERE\n  $__timeFilter(measure_timestamp)\nORDER BY 1"
    }
   ]
  }
 ]
}